name: OpenHAB Add-on build
on:
  push:
    tags: [ "*.*.*" ]
  workflow_dispatch:
      inputs:
        version:
          description: 'Version'
          required: true
          default: '0.0.0'
          type: string
jobs:
  build-oh-addon:
    runs-on: ubuntu-22.04
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: zulu
      - name: Get HAB Speaker version
        id: get_version
        run: |
          EVENT_NAME=$(echo "${{ github.event_name }}")
          echo "trigger name $EVENT_NAME"
          if [ "$EVENT_NAME" = "workflow_dispatch" ]; then
            echo "Get version from inputs"
            USE_VERSION=$(echo "${{ github.event.inputs.version }}")
          else
              echo "Get version from tag name"
            USE_VERSION=$(echo $GITHUB_REF | cut -d / -f 3)
          fi
          echo "Building version $USE_VERSION"
          echo "VERSION=$USE_VERSION" >> $GITHUB_OUTPUT
      - name: Checkout HABSpeaker
        uses: actions/checkout@v3
        with:
          repository: GiviMAD/openhab-addons
          ref: refs/tags/habspeaker-${{ steps.get_version.outputs.VERSION }}
          path: marketplace-addons
      - name: Maven Build
        run: |
          cd ./marketplace-addons
          mvn clean install -pl :org.openhab.voice.habspeaker
      - name: Upload add-on jar
        uses: actions/upload-artifact@v3
        with:
          name: HABSpeaker_Addon
          path: marketplace-addons/bundles/org.openhab.voice.habspeaker/target/org.openhab.voice.habspeaker-3.4.3-SNAPSHOT.jar
          retention-days: 5
  create_release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-oh-addon]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        - uses: actions/checkout@v3
        - name: Get HAB Speaker version
          id: get_version
          run: |
            EVENT_NAME=$(echo "${{ github.event_name }}")
            echo "trigger name $EVENT_NAME"
            if [ "$EVENT_NAME" = "workflow_dispatch" ]; then
              echo "Get version from inputs"
              USE_VERSION=$(echo "${{ github.event.inputs.version }}")
            else
                echo "Get version from tag name"
              USE_VERSION=$(echo $GITHUB_REF | cut -d / -f 3)
            fi
            echo "Building version $USE_VERSION"
            echo "VERSION=$USE_VERSION" >> $GITHUB_OUTPUT
        - uses: actions/download-artifact@v3
        - name: Check tree again
          run: ls -R
        - name: release
          uses: softprops/action-gh-release@v1
          id: create_release
          with:
            tag_name: release_addon_${{ steps.get_version.outputs.VERSION }}
            name: HAB Speaker OpenHAB add-on v${{ steps.get_version.outputs.VERSION }}
            draft: false
            prerelease: false
            generate_release_notes: false
            body: Add-on [HABSpeaker v${{ steps.get_version.outputs.VERSION }}](https://github.com/GiviMAD/openhab-addons/releases/tag/habspeaker-${{ steps.get_version.outputs.VERSION }}) for [OpenHAB](https://www.openhab.org)
            files: |
              HABSpeaker_Addon/org.openhab.voice.habspeaker-3.4.3-SNAPSHOT.jar
          env:
            GITHUB_TOKEN: ${{ github.token }}
